# Default initial positions for rob robot's ros2_control fake system

initial_positions:
  joint1: 0.0
  joint2: 0.0
  joint3: 0.0
  joint4: 0.0
  joint5: 0.0
  virtual_joint6: 0.0
  joint_R_gear: 0.0
